### ISSUE TITLE
Update table reads for large files and improve memory footprints

### ISSUE THREAD

**Issue by fran-vallejo** [NASA-PDS/pds4-jparser#21]
**Is your feature request related to a problem? Please describe.**
When validating a _Table_Delimited_ PDS4 product, validate tool takes as much memory as 12 times the size of the data file. This makes difficult to validate products close to the gigabyte (like highgate magnetometer data) as they require to run validate with a large portion of the available memory.

See the following other tickets for more details. Any improvements should be sure the following tickets are also verified as successfully tested.
* NASA-PDS/transform#2
* NASA-PDS/validate#155
* NASA-PDS/validate#189

Debugging this issue I found that most of the memory allocation is in pds4-jparser's gov.nasa.pds.objectAccess.TableReader class, specifically in line 120 which loads the whole data file. 
`delimitedRecordList = csvReader.readAll();`

**Describe the solution you'd like**
An alternative table delimited read implementation that does not consume so much memory.

**Describe alternatives you've considered**
Reading the data sequentially using csvReader.readNex(); but the problem of this approach it doesn't consider cases where the current row pointer is reset while reading the file, and that might happen as TableReader declares:
`public TableRecord getRecord(int index) throws IllegalArgumentException, IOException
public void setCurrentRow(int row)`  

**Additional context**
Memory footprint validating a 720MB product:
![CurrentFootprint](https://user-images.githubusercontent.com/52571100/76854148-e1028d00-684e-11ea-873d-e269f582afd9.png)

Memory footprint validating a 720MB product with the alternative described:
![ModifiedFootprint](https://user-images.githubusercontent.com/52571100/76854210-f8417a80-684e-11ea-8365-642fa63de7ca.png)

Modifications to TableReader used for the second case:
@@ -65,7 +65,7 @@ public class TableReader {
-       private List<String[]> delimitedRecordList;
+       //private List<String[]> delimitedRecordList; 
@@ -117,7 +117,7 @@ public class TableReader {
-                       delimitedRecordList = csvReader.readAll();
+                       //delimitedRecordList = csvReader.readAll();
@@ -188,7 +188,7 @@ public class TableReader {
-                       String[] recordValue = delimitedRecordList.get(currentRow-1);
+                       String[] recordValue = csvReader.readNext();

**Comment by jordanpadams** [comment]
thanks @fran-vallejo . this is related to NASA-PDS-Incubator/validate#189 and NASA-PDS-Incubator/transform#2, and I think we know what we need to do here, we just need to get the time to fix it. we will move this is up in priority for our next release cycle

**Comment by fran-vallejo** [comment]
Opps.. I didn't saw the related ticket in validate. 
Many thanks!

**Comment by jordanpadams** [comment]
@fran-vallejo no problem! this is really where it belongs.

**Comment by jordanpadams** [comment]
June schedule status: Delayed due to higher priority bug fixes and limited availability of resources.

**Comment by jordanpadams** [comment]
August Schedule Status: Delayed due to personnel being pulled off onto M2020

**Comment by jordanpadams** [comment]
September schedule status: Issue de-scoped from build due to M2020 work. Moving to next Build

**Comment by tloubrieu-jpl** [comment]
@hhlee445 can you estimate when you think you can close this issue ? Thanks

**Comment by hhlee445** [comment]
> @hhlee445 can you estimate when you think you can close this issue ? Thanks
@tloubrieu-jpl  I’m  busy this week to make a delivery for M20. I will try to finish this ticket by next week.

**Comment by hhlee445** [comment]
@tloubrieu-jpl  I’m  busy this week to make a delivery for M20. I will try to finish this ticket by next week.

**Comment by jordanpadams** [comment]
October schedule status: Task could not be completed in time for delivery to I&T and has been deferred to B11.1

**Comment by hhlee445** [comment]
@jordanpadams validate  issue_189 is implemented and it is validating a binary file>2GB. however, I want to test with a large CSV file, do you have any test data?

**Comment by jordanpadams** [comment]
@hhlee445 i just create a quick file that should validate (may need to check the number of records I included). On pds-gamma

http://pds-gamma.jpl.nasa.gov/software/test-data/validate/validate-189/validate.(csv|xml)

Note: this maps to /data/http on the machine.

here is the run off a previous version of validate:

```
PDS Validate Tool Report

Configuration:
   Version                       1.24.0-SNAPSHOT
   Date                          2020-11-01T21:37:35Z

Parameters:
   Targets                       [file:/Users/jpadams/test/ccb266/validate189.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/test/validate-1.24.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/test/ccb266/validate189.xml
    Begin Content Validation: file:/Users/jpadams/test/ccb266/validate189.csv
      ERROR  [error.table.bad_file_read]   table 1: Error occurred while trying to read table: null
    End Content Validation: file:/Users/jpadams/test/ccb266/validate189.csv
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.table.bad_file_read

End of Report
Completed execution in 4038 ms
```

**Comment by jordanpadams** [comment]
@fran-vallejo this should be fixed, so feel free to check out the latest version of pds4-jparser and validate to see if it improves performance for you.

**Comment by fran-vallejo** [comment]
Hi @jordanpadams, I have checked several products against the latest version of validate and the memory footprint has improved a lot, staying most of the time under the size of the product under validation. Thanks!

Unfortunately one of the products, that validates fine with 1.24.0 crashes with 1.25.0-SNAPSHOT. 
I have tested it using the current master for both pds4-jparser and validate, specifically:
- pds4-jparser commit **f1587d94e3ac0115e872b31202c3b4aa613e9c15**
- validate commit          **a5d6021e3eb64601e6126c792bb7e7a31e67de4b**

You can download the product from: (The link will be live until Dec. 15th)
https://esabox.esa.int/owncloud/index.php/s/xLlWOJMSRVDWW2s
Pass: Jparser#21

Anyway if you prefer, I can open a separate ticket for this.
Cheers,

```
PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-12-03T17:33:06Z

Parameters:
   Targets                       [file:/home/fvallejo/Downloads/mag/mag_cal_sc_ob_s9_e2k_00000_20181105.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/fvallejo/Software/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json
   Non Registered Contexts File  /home/fvallejo/git/local_context_products.json



Product Level Validation Results

  PASS: gov.nasa.pds.validate.ValidateLauncher
      WARNING  [warning.product_not_registered]   Non-registered context products should only be used during archive development. All context products must be registered for a valid, released archive bundle. 
        1 product validation(s) completed
....................................................................java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:134)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:236)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1256)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1494)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1540)
Caused by: java.nio.BufferUnderflowException
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at gov.nasa.pds.objectAccess.ByteWiseFileAccessor.readRecordBytes(ByteWiseFileAccessor.java:237)
	at gov.nasa.pds.objectAccess.TableReader.getTableRecord(TableReader.java:233)
	at gov.nasa.pds.objectAccess.TableReader.getRecord(TableReader.java:214)
	at gov.nasa.pds.tools.validate.content.table.RawTableReader.getRecord(RawTableReader.java:173)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:467)
	... 12 more

  FAIL: file:/home/fvallejo/Downloads/mag/mag_cal_sc_ob_s9_e2k_00000_20181105.xml
      ERROR  [error.validation.internal_error]   Error executing validationTask: java.nio.BufferUnderflowException
        2 product validation(s) completed

Summary:

  1 error(s)
  1 warning(s)

  Product Validation Summary:
    1          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.internal_error
    1            warning.product_not_registered

End of Report
Completed execution in 157130 ms

```

**Comment by jordanpadams** [comment]
@fran-vallejo thanks. a new ticket would be great and we will add this to the top of our list.
