### ISSUE TITLE
SNAPSHOT dependencies in 2.0.0 release

### ISSUE THREAD

**Issue by markBowman** [NASA-PDS/pds4-jparser#40]
The 2.0.0 release of pds4-jparser contains SNAPSHOT dependencies in its pom.xml. This means that this release can not be built using publicly accessible maven repositories. More importantly, downstream projects that depend on pds4-jparsers:2.0.0 also can not be built using public maven repositories. For example, the current master branch of https://github.com/NASA-PDS/validate.
The two SNAPSHOT dependencies are gov.nasa.jpl.ammos.ids.vicario:vicario:48.0.3-SNAPSHOT and com.opencsv:opencsv:5-4-SNAPSHOT.

Potential fix: Release pds4-jparser:2.0.1 with no SNAPSHOT dependencies.

**Comment by jordanpadams** [comment]
@markBowman thanks for reaching out here. unfortunately, right now those SNAPSHOTS need to stay in there because they are forks of projects that we don't currently own. we will look to get those released to maven central down the road.

once workaround for this would be to do what we do in our POMs:
1. [copy the directory](https://github.com/NASA-PDS/pds4-jparser/tree/master/repo) we have in pds4-jparser to your project basedir
2. update your POM to look for the local "maven repo" to find the SNAPSHOTs:

```xml
  <repositories>
    <repository>
      <id>project.local</id>
      <name>project</name>
      <url>file:${project.basedir}/repo</url>
    </repository>
  </repositories>
```

obviously not an ideal solution, but a workaround at least

**Comment by tdddblog** [comment]
@jordanpadams The issue remains in version 2.0.2.  Instead of those hacks with copying directories, can we rename custom `opencsv` and `vicario` to  `opencsv-pds` and `vicario-pds` and don't use snapshots.

**Comment by jordanpadams** [comment]
@tdddblog can you test using the 2.1.0-SNAPSHOT version of pds4-jparser? i deployed SNAPSHOT versions of the JARs to maven central, so they should be picked up now. you will just need to add snapshots to your list of repositories.

```
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

@markBowman let me know if this will work for the time being. i can work to tag a relaese, but it is a little more complicated when dealing with maven central

**Comment by jordanpadams** [comment]
@markBowman this should now be fixed in [the latest version](https://github.com/NASA-PDS/pds4-jparser/releases/latest) of pds4-jparser

**Comment by markBowman** [comment]
> @markBowman this should now be fixed in [the latest version](https://github.com/NASA-PDS/pds4-jparser/releases/latest) of pds4-jparser

Thank you :-)
