### ISSUE TITLE
Parse failure for table fields of type ASCII_Numeric_Base16

### ISSUE THREAD

**Issue by mbtaylor** [NASA-PDS/pds4-jparser#57]
## 🐛 Describe the bug
This code in [FieldType.java](https://github.com/NASA-PDS/pds4-jparser/blob/main/src/main/java/gov/nasa/pds/label/object/FieldType.java) looks wrong:
```
   ASCII_NUMERIC_BASE16("ASCII_Numeric_Base16", new NumericTextFieldAdapter(), true),
```
in view of the [ASCII_Numeric_Base16 type definitiion](https://pds.jpl.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1I00.html#N205352130).
The [NumericTextFieldAdapter](https://github.com/NASA-PDS/pds4-jparser/blob/main/src/main/java/gov/nasa/pds/objectAccess/table/NumericTextFieldAdapter.java) includes code like:
```
    @Override
    public long getLong(byte[] buf, int offset, int length, int startBit, int stopBit) {
        return Long.parseLong(getString(buf, offset, length, startBit, stopBit).trim());
    }
```
which wil fail (with a `java.lang.NumberFormatException`) if fed the kind of text expected for Base16.

## 📜 To Reproduce
try to use pds4-jparser to read values from a table with `ASCII_Numeric_Base16` data.  I have an example data file of this sort, but the provider doesn't want to post it publicly.

## 📚 Version of Software Used
I'm looking at the source code on `master` at time of writing, 194b5f9.

## Suggested fix
I suggest either to introduce a new `RadixTextFieldAdapter` for use with `ASCII_Numeric_Base16`, `ASCII_Numeric_Base8` and `ASCII_Numeric_Base2` (I have prototyped this and can make a Pull Request on request).  Failing that, fall back to the `DefaultFieldAdapter` for `ASCII_Numeric_Base16`, as is already done for `ASCII_Numeric_Base8` and `ASCII_Numeric_Base2`.

**Comment by msbentley** [comment]
Thanks @mbtaylor - @jordanpadams FYI this is coming from a real-world case of ExoMars TGO data which uses unsigned integers written to a data file as hex, and failing when trying to read in Topcat. It would be great to get this one resolved sooner rather than later. Thanks!

**Comment by jordanpadams** [comment]
thanks @msbentley we will add to the backlog

@rchenatjpl can you help us with a simple test file for this?

**Comment by jordanpadams** [comment]
@msbentley @mbtaylor is this a blocker for anything right now? I am thinking this is a medium severity, but can upgrade to high/critical if it is blocking data processing.

**Comment by rchenatjpl** [comment]
@mbtaylor Here's a label expecting two ASCII_Numeric_Base16 fields. Its data file has three lines. The first two lines have good values, then the third replaces a 'B' in one of the hex fields with a 'G', and validate picks that up and passes the first two. I got the same results with validate versions 1.17.5 and 2.2.0. So how can I modify these inputs to see the bug? Thanks
[Archive.zip](https://github.com/NASA-PDS/pds4-jparser/files/9114173/Archive.zip)

**Comment by msbentley** [comment]
This is not a validate bug, per se, though I was going to see if I could trigger it there. My guess was to try to set a min/max value and try for a numeric comparison, but I haven't tried yet...

@jordanpadams it cropped up in a data review that we just started, but I don't know if anyone else tried using Topcat and hence jparser for it. So medium priority is probably OK

**Comment by mbtaylor** [comment]
This is not a blocker from my point of view.  I have already implemented a workaround in my code that avoids encountering this issue.  I reported it so that you can fix the library in case other downstream code is attempting to read numeric values from fields of this type.  If no downstream code is in fact reading numeric values from ASCII_Numeric_Base16 (presumably your validate does not) then I guess this will not cause problems elsewhere.

**Comment by mbtaylor** [comment]
To clarify: by "read numeric values" I mean if you call e.g.  `FieldType.ASCII_NUMERIC_BASE16.getAdapter().getLong()` on a buffer containing data for a field of that type.

**Comment by msbentley** [comment]
Hi @rchenatjpl, @jordanpadams I tried to force validate to do some numerical comparisons so that it actually read the data, but things worked that I believe should have failed, so perhaps validate is not treating base whatever values as numeric?

e.g. I created something with:
```
                    <Field_Character>
                        <name>ROW_DATA</name>
                        <field_location unit="byte">1</field_location>
                        <data_type>ASCII_Numeric_Base16</data_type>
                        <field_length unit="byte">2</field_length>
                        <Special_Constants>
                            <valid_maximum>5</valid_maximum>
                        </Special_Constants>
                    </Field_Character>
```
with a simple case of 2 reps and 2 records:
```
... 0102 ...
... 0AFF ...
```
and I would have expected validate to complain that the values in record two (i.e. 10 and 255) are over the valid maximum (5) but this is not the case...

**Comment by jordanpadams** [comment]
@mbtaylor sorry for the delay on this fix. feel free to grap the latest SNAPSHOT [here](https://github.com/NASA-PDS/pds4-jparser/releases) and give it a spin. (it should be built and deployed to Maven central in the next ~15 minutes)

if you need us to tag a new stable release, please let us know.

**Comment by jordanpadams** [comment]
👍
